# Generated by Django 3.0.5 on 2020-05-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='Year')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20)),
                ('min_temp', models.IntegerField(db_column='Minimum')),
                ('avg_temp', models.IntegerField(db_column='Average')),
                ('max_temp', models.IntegerField(db_column='Maximum')),
            ],
        ),
        migrations.DeleteModel(
            name='Crops',
        ),
    ]
