# Generated by Django 3.0.6 on 2020-06-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_dashboard', '0003_historical_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='Year')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20)),
                ('min_temp', models.FloatField(db_column='Min Temperature')),
                ('avg_temp', models.FloatField(db_column='Avg Temperature')),
                ('max_temp', models.FloatField(db_column='Max Temperature')),
                ('avg_prec', models.FloatField(db_column='Avg Precipitation')),
                ('avg_rel_humid', models.FloatField(db_column='Avg Relative Humidity')),
                ('avg_pressure', models.FloatField(db_column='Avg Pressure')),
            ],
        ),
        migrations.RenameModel(
            old_name='Historical_records',
            new_name='Daily_records',
        ),
    ]
