# Generated by Django 3.0.6 on 2020-09-22 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sg_dashboard', '0006_auto_20200915_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
