# Generated by Django 3.0.6 on 2020-09-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sg_dashboard', '0007_delete_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_real_time',
            name='pH',
        ),
        migrations.RemoveField(
            model_name='daily_real_time',
            name='pressure',
        ),
    ]
